# Use an official Python runtime as a parent image
FROM python:3.10

# Install cron
RUN apt-get update && apt-get -y install cron

# Set the working directory to /app
WORKDIR /app

# Copy the main requirements file and install dependencies
COPY requirements.txt /app/
RUN pip install -r requirements.txt

# Copy the code_review requirements file and install its dependencies
COPY code_review/requirements.txt /app/code_review/requirements.txt
RUN pip install -r /app/code_review/requirements.txt

# Now copy the rest of the application code
COPY . /app

# Make port 3030 available to the world outside this container
EXPOSE 3030

# Ensure the trainer.py script is executable
RUN chmod +x /app/trainer.py

# Run the trainer.py script
# RUN /usr/bin/python3 /app/trainer.py

# Apply the cron job
RUN chmod +x /app/cron
RUN crontab /app/cron

# Copy the entrypoint script into the container at /app
COPY entrypoint.sh /app/

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Run the entrypoint script
CMD ["/app/entrypoint.sh"]

# CMD ["cron", "-f"]
