# Use an official Python runtime as a parent image
FROM python:3.10

# Install cron
RUN apt-get update && apt-get -y install cron

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 3030 available to the world outside this container
EXPOSE 3030

RUN chmod +x /app/trainer.py

# Run trainer.py immediately when the container starts
RUN /usr/bin/python3 /app/trainer.py

# Apply the cron job
RUN chmod +x /app/cron
RUN crontab /app/cron

# Copy the entrypoint script into the container at /app
COPY entrypoint.sh /app/

# Make the script executable
RUN chmod +x /app/entrypoint.sh

# Run the entrypoint script
# CMD ["/app/entrypoint.sh"]

CMD ["cron", "-f"]