version: '3.8'

services:
  ml-api:
    container_name: interact-ml
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
